package com.xuwanjin.inchoate.model;

public enum Section {
    THE_WORLD_THIS_WEEK,
    LEADERS,
    LETTERS,
    BRIEFING,
    UNITED_STATES,
    THE_AMERICAS,
    ASIA,
    CHINA,
    MIDDLE_EAST_AND_AFRICA,
    EUROPE,
    BRITAIN,
    INTERNATIONAL,
    BUSINESS,
    FINANCE_AND_ECONOMICS,
    SCIENCE_AND_TECHNOLOGY,
    BOOKS_AND_ARTS,
    ECONOMICS_AND_FINANCIAL_INDICATORS,
    GRAPHIC_DETAIL,
    OBITUNARY,

}
